return {
  addition_op = 1,
  subtraction_op = 2,
  multiplication_op = 3,
  division_op = 4,
  modulus_op = 5,
  power_op = 6,
  concatenation_op = 7,
  not_equal_op = 8,
  equal_op = 9,
  less_than_op = 10,
  less_or_equal_op = 11,
  greater_than_op = 12,
  greater_or_equal_op = 13,
  and_op = 14,
  or_op = 15,
}
