return {
  break_statement = 1,
  nil_literal_expression = 2,
  boolean_literal_expression = 3,
  number_literal_expression = 4,
  do_statement = 5,
  return_statement = 6,
  string_literal_expression = 7,
  variable_argument_expression = 8,
  function_expression = 9,
  parameter_declaration = 10,
  table_literal_expression = 11,
  field_declaration = 12,
  binary_op_expression = 13,
  unary_op_expresssion = 14,
}
